Modify quarantine attribute removal method
Replace xattr command with find to remove quarantine attribute.

diff --git a/createinstalliso b/createinstalliso
--- a/createinstalliso
+++ b/createinstalliso
@@ -506,7 +506,7 @@ main() {
 
         echo "Copying installer application..."
         ditto "${original_installer_application_path}" "${modified_installer_application_path}" >/dev/null || exit_with_status 220 "Failed to copy installer application."
-        xattr -drs "com.apple.quarantine" "${modified_installer_application_path}" >/dev/null || exit_with_status 219 "Failed to remove extended attribute com.apple.quarantine."
+        find "${modified_installer_application_path}" -exec xattr -d com.apple.quarantine {} \; 2>/dev/null || true # "${modified_installer_application_path}" >/dev/null || exit_with_status 219 "Failed to remove extended attribute com.apple.quarantine."
 
         if [[ "${global_patch_macos_sierra_installer_application}" == "true" ]]; then
             echo "Patching macOS Sierra installer application..."
